/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-14 17:31:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" />\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Cart Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("#customers {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#customers td, #customers th {\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#customers tr:nth-child(even){background-color: #f2f2f2;}\r\n");
      out.write("\r\n");
      out.write("#customers tr:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("#customers th {\r\n");
      out.write("  padding-top: 12px;\r\n");
      out.write("  padding-bottom: 12px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #4CAF50; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 8px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".button3 {background-color: #f44336;} /* Red */ \r\n");
      out.write(".btn-incre {\r\n");
      out.write("box-shadow:none;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("}\r\n");
      out.write(".btn-decre{\r\n");
      out.write("box-shadow:none;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script>\r\n");
      out.write("function myFunction() {\r\n");
      out.write("	  alert(\"Payment is Successful\");\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"d-flex py-3\">\r\n");
      out.write("<h1 align=\"center\">Your Cart</h1>\r\n");
      out.write("\r\n");
      out.write("<table id=\"customers\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th scope=\"col\">Name</th>\r\n");
      out.write("<th scope=\"col\">Category</th>\r\n");
      out.write("<th scope=\"col\">Price</th>\r\n");
      out.write("<th scope=\"col\">Buy Now</th>\r\n");
      out.write("<th scope=\"col\">Cancel</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Cottage Cheese Burger</td>\r\n");
      out.write("<td>Vegetarian</td>\r\n");
      out.write("<td>Rs.190</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"1\" class=\"form-input\">\r\n");
      out.write("<div class=\"form-group d-flex justify-content-between\">\r\n");
      out.write("<a class=\"btn btn-sm btn-decre\" href=\" \"><i class=\"fas fa-minus-square\"></i></a>\r\n");
      out.write("<input type=\"text\" name=\"quantity\" class=\"form-control\" value=\"1\" readonly>\r\n");
      out.write("<a class=\"btn btn-sm btn-incre\"><i class=\"fas fa-plus-square\"></i></a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button class=\"button button3\">Cancel</button>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Crepe</td>\r\n");
      out.write("<td>Vegetarian</td>\r\n");
      out.write("<td>Rs.200</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"1\" class=\"form-input\">\r\n");
      out.write("<div class=\"form-group d-flex justify-content-between\">\r\n");
      out.write("<a class=\"btn btn-sm btn-decre\" href=\" \"><i class=\"fas fa-minus-square\"></i></a>\r\n");
      out.write("<input type=\"text\" name=\"quantity\" class=\"form-control\" value=\"2\" readonly>\r\n");
      out.write("<a class=\"btn btn-sm btn-incre\"><i class=\"fas fa-plus-square\"></i></a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button class=\"button button3\">Cancel</button>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Lemonade</td>\r\n");
      out.write("<td>Drinks</td>\r\n");
      out.write("<td>Rs.120</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"1\" class=\"form-input\">\r\n");
      out.write("<div class=\"form-group d-flex justify-content-between\">\r\n");
      out.write("<a class=\"btn btn-sm btn-decre\" href=\" \"><i class=\"fas fa-minus-square\"></i></a>\r\n");
      out.write("<input type=\"text\" name=\"quantity\" class=\"form-control\" value=\"1\" readonly>\r\n");
      out.write("<a class=\"btn btn-sm btn-incre\"><i class=\"fas fa-plus-square\"></i></a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button class=\"button button3\">Cancel</button>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<h3 align=\"center\">Total Price: Rs.510</h3>\r\n");
      out.write("\r\n");
      out.write("<a class=\"mx-3 btn btn-primary\" href=\"#\" align=\"center\"><button onClick=\"myFunction()\" align=\"center\"><h2>Check Out</h2></button></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
